/*
===========================================================================
modelconverter - Quake3 .shader file reader and writer.

The writer turns the materials carried on each mc_surface_t into a Q3
shader script: one stanza per unique shader name, using the surface's
texture as the first stage's `map` and emitting `cull disable`,
`surfaceparm trans`, `blendFunc blend`, normal/emissive comments and so
on according to the recorded glTF material flags.

The reader parses an existing `.shader` file and, for any surface whose
shader name matches a stanza, copies the first stage `map` path into the
surface's texture slot and lifts a few common flags (cull, surfaceparm,
blendFunc, alphaFunc) back onto the material.  This lets a `.shader`
authored by hand drive the textures referenced by an MD3.

The parser is intentionally tiny: it understands nested {}, line and
block comments, "quoted strings" and whitespace-separated tokens.
That is sufficient for everything WoP and ioquake3 ship.
===========================================================================
*/

#include "mc_common.h"

#include <ctype.h>
#include <string.h>

/* ------------------------------------------------------------------ */
/* Tiny string helpers                                                */
/* ------------------------------------------------------------------ */

static int sh_is_token_char(int c) {
	return c && !isspace(c) && c != '{' && c != '}' && c != '"';
}

/* Skip whitespace and // / *-style comments.  Returns the new cursor. */
static const char *sh_skip(const char *p) {
	for (;;) {
		while (*p && isspace((unsigned char)*p))
			++p;
		if (p[0] == '/' && p[1] == '/') {
			while (*p && *p != '\n')
				++p;
			continue;
		}
		if (p[0] == '/' && p[1] == '*') {
			p += 2;
			while (*p && !(p[0] == '*' && p[1] == '/'))
				++p;
			if (*p)
				p += 2;
			continue;
		}
		return p;
	}
}

/* Read the next token into `out` (size `out_size`).  Returns the cursor
   just past the token, or NULL at end-of-input. */
static const char *sh_token(const char *p, char *out, size_t out_size) {
	p = sh_skip(p);
	if (!*p) {
		if (out_size)
			out[0] = 0;
		return NULL;
	}
	size_t i = 0;
	if (*p == '{' || *p == '}') {
		if (out_size > 1) {
			out[0] = *p;
			out[1] = 0;
		}
		return p + 1;
	}
	if (*p == '"') {
		++p;
		while (*p && *p != '"') {
			if (i + 1 < out_size)
				out[i++] = *p;
			++p;
		}
		if (*p == '"')
			++p;
	} else {
		while (sh_is_token_char((unsigned char)*p)) {
			if (i + 1 < out_size)
				out[i++] = *p;
			++p;
		}
	}
	if (out_size)
		out[i] = 0;
	return p;
}

static void sh_lower(char *s) {
	for (; *s; ++s)
		*s = (char)tolower((unsigned char)*s);
}

/* ------------------------------------------------------------------ */
/* Writer                                                              */
/* ------------------------------------------------------------------ */

/* Strip a trailing extension (.tga/.jpg/.png/...) and any leading "./" so
   the value matches what the engine expects in `map` directives. */
static void shader_clean_path(char *p) {
	if (p[0] == '.' && p[1] == '/')
		memmove(p, p + 2, strlen(p + 2) + 1);
	mc_strip_extension(p);
}

static int shader_already_emitted(const mc_model_t *m, int upto, const char *name) {
	for (int i = 0; i < upto; ++i) {
		if (!strcmp(m->surfaces[i].shader, name))
			return 1;
	}
	return 0;
}

int mc_save_q3shader(const char *path, const mc_model_t *m) {
	FILE *f = fopen(path, "wb");
	if (!f) {
		MC_ERR("error: cannot open '%s' for writing\n", path);
		return -1;
	}

	fprintf(f, "// generated by modelconverter\n");

	int written = 0;
	for (int i = 0; i < m->numSurfaces; ++i) {
		const mc_surface_t *s = &m->surfaces[i];
		if (!s->shader[0])
			continue;
		if (shader_already_emitted(m, i, s->shader))
			continue;

		char tex[MC_MAX_PATH];
		mc_q_strncpy(tex, s->texture[0] ? s->texture : s->shader, sizeof(tex));
		shader_clean_path(tex);

		fprintf(f, "\n%s\n{\n", s->shader);
		/* If we round-tripped the original body through glTF extras,
		   emit it verbatim so every stage / blendFunc / tcMod / rgbGen
		   survives unchanged. Otherwise reconstruct a best-effort
		   stanza from the parsed metadata. */
		if (s->q3_shader_body && s->q3_shader_body[0]) {
			fputs(s->q3_shader_body, f);
			if (s->q3_shader_body[strlen(s->q3_shader_body) - 1] != '\n')
				fputc('\n', f);
			fprintf(f, "}\n");
			++written;
			continue;
		}
		if (s->two_sided)
			fprintf(f, "\tcull disable\n");
		if (s->surfaceparm[0])
			fprintf(f, "\tsurfaceparm %s\n", s->surfaceparm);
		else if (s->alpha_mode == 2)
			fprintf(f, "\tsurfaceparm trans\n");
		/* qer_editorimage helps GtkRadiant pick the texture for previews. */
		if (tex[0])
			fprintf(f, "\tqer_editorimage %s\n", tex);

		/* Optional normal / emissive maps as opengl2-style stages.  The
		   engine ignores them on the renderergl1 path; the comments make
		   it obvious which file fed them. */
		if (s->normal_map[0]) {
			char nm[MC_MAX_PATH];
			mc_q_strncpy(nm, s->normal_map, sizeof(nm));
			shader_clean_path(nm);
			fprintf(f, "\tnormalMap %s\n", nm);
		}
		if (s->normal_height_map[0]) {
			char nh[MC_MAX_PATH];
			mc_q_strncpy(nh, s->normal_height_map, sizeof(nh));
			shader_clean_path(nh);
			/* opengl2 picks up the alpha channel as height when the file
			   ends in _nh; the directive is the same. */
			fprintf(f, "\tnormalMap %s\n", nh);
		}
		if (s->mr_map[0]) {
			char mr[MC_MAX_PATH];
			mc_q_strncpy(mr, s->mr_map, sizeof(mr));
			shader_clean_path(mr);
			fprintf(f, "\tspecularMap %s\n", mr);
		}

		/* Primary stage. */
		fprintf(f, "\t{\n");
		if (tex[0])
			fprintf(f, "\t\tmap %s\n", tex);
		if (s->alpha_mode == 1) {
			int cutoff = (int)(s->alpha_cutoff * 255.0f);
			if (cutoff <= 0)
				cutoff = 128;
			fprintf(f, "\t\talphaFunc GE128\n");
			fprintf(f, "\t\tdepthWrite\n");
			fprintf(f, "\t\t// alphaCutoff %.3f (%d)\n", s->alpha_cutoff, cutoff);
		} else if (s->alpha_mode == 2) {
			fprintf(f, "\t\tblendFunc blend\n");
		}
		fprintf(f, "\t\trgbGen identity\n");
		fprintf(f, "\t}\n");

		/* Optional emissive overlay. */
		if (s->emissive_map[0] ||
			(s->emissive_factor[0] + s->emissive_factor[1] + s->emissive_factor[2]) > 0.0f) {
			char em[MC_MAX_PATH];
			mc_q_strncpy(em, s->emissive_map[0] ? s->emissive_map : tex, sizeof(em));
			shader_clean_path(em);
			fprintf(f, "\t{\n");
			fprintf(f, "\t\tmap %s\n", em);
			fprintf(f, "\t\tblendFunc add\n");
			fprintf(f, "\t\trgbGen const ( %.3f %.3f %.3f )\n", s->emissive_factor[0], s->emissive_factor[1],
					s->emissive_factor[2]);
			fprintf(f, "\t}\n");
		}

		fprintf(f, "}\n");
		++written;
	}

	fclose(f);
	MC_LOG("wrote %s (%d shader stanza%s)\n", path, written, written == 1 ? "" : "s");
	return 0;
}

/* ------------------------------------------------------------------ */
/* Reader                                                              */
/* ------------------------------------------------------------------ */

/* Apply a single stanza body to all matching surfaces in `m`. */
static void shader_apply(mc_model_t *m, const char *name, const char *body, size_t body_len) {
	int matched = 0;
	for (int i = 0; i < m->numSurfaces; ++i) {
		if (!strcasecmp(m->surfaces[i].shader, name)) {
			matched = 1;
			break;
		}
		char surf_stem[MC_MAX_PATH];
		mc_q_strncpy(surf_stem, m->surfaces[i].shader, sizeof(surf_stem));
		mc_strip_extension(surf_stem);
		if (!strcasecmp(surf_stem, name)) {
			matched = 1;
			break;
		}
	}
	if (!matched)
		return;

	/* Walk the body collecting flags + every stage's map / blendfunc /
	   alphafunc / tcGen so we can pick the best diffuse stage instead
	   of always grabbing the first one (WoP shaders frequently put
	   animated water or decal effects in stage 0 and the actual base
	   texture in a later stage). */
	const char *p = body;
	const char *end = body + body_len;
	char tok[MC_MAX_PATH];
	int two_sided = -1;
	char surfaceparm[64];
	surfaceparm[0] = 0;
	char deform[32];
	deform[0] = 0;
	char editor_image[MC_MAX_PATH];
	editor_image[0] = 0;
	char normal_map[MC_MAX_PATH];
	normal_map[0] = 0;
	char normal_height_map[MC_MAX_PATH];
	normal_height_map[0] = 0;
	char emissive_map[MC_MAX_PATH];
	emissive_map[0] = 0;

	enum { MAX_STAGES = 16 };
	struct stage_info {
		char map[MC_MAX_PATH];
		int has_blendfunc;	  /* 0 = none (GL_ONE GL_ZERO opaque) */
		int alpha_mode;		  /* -1 unset, 0 opaque, 1 mask, 2 blend */
		float alpha_cutoff;
		int env_mapped;		  /* tcGen environment / tcMod turb */
	} stages[MAX_STAGES];
	int num_stages = 0;
	int in_stage = 0;
	struct stage_info cur;
	memset(&cur, 0, sizeof(cur));
	cur.alpha_mode = -1;
	cur.alpha_cutoff = 0.5f;

	while (p && p < end) {
		const char *next = sh_token(p, tok, sizeof(tok));
		if (!next || next > end)
			break;
		p = next;
		if (!tok[0])
			break;

		if (!strcmp(tok, "{")) {
			in_stage = 1;
			memset(&cur, 0, sizeof(cur));
			cur.alpha_mode = -1;
			cur.alpha_cutoff = 0.5f;
			continue;
		}
		if (!strcmp(tok, "}")) {
			if (in_stage && num_stages < MAX_STAGES)
				stages[num_stages++] = cur;
			in_stage = 0;
			continue;
		}

		char low[MC_MAX_PATH];
		mc_q_strncpy(low, tok, sizeof(low));
		sh_lower(low);

		if (!in_stage) {
			if (!strcmp(low, "cull")) {
				char arg[64];
				p = sh_token(p, arg, sizeof(arg));
				sh_lower(arg);
				if (!strcmp(arg, "disable") || !strcmp(arg, "none") || !strcmp(arg, "twosided"))
					two_sided = 1;
				else
					two_sided = 0;
			} else if (!strcmp(low, "surfaceparm")) {
				p = sh_token(p, surfaceparm, sizeof(surfaceparm));
			} else if (!strcmp(low, "deformvertexes")) {
				char arg[64];
				p = sh_token(p, arg, sizeof(arg));
				sh_lower(arg);
				if (!strcmp(arg, "autosprite") || !strcmp(arg, "autosprite2"))
					mc_q_strncpy(deform, arg, sizeof(deform));
			} else if (!strcmp(low, "qer_editorimage")) {
				if (!editor_image[0])
					p = sh_token(p, editor_image, sizeof(editor_image));
			} else if (!strcmp(low, "normalmap") || !strcmp(low, "bumpmap")) {
				/* Treat _nh-suffixed paths as normal+height. */
				char arg[MC_MAX_PATH];
				p = sh_token(p, arg, sizeof(arg));
				char stem[MC_MAX_PATH];
				mc_q_strncpy(stem, arg, sizeof(stem));
				mc_strip_extension(stem);
				size_t slen = strlen(stem);
				if (slen >= 3 && !strcasecmp(stem + slen - 3, "_nh"))
					mc_q_strncpy(normal_height_map, arg, sizeof(normal_height_map));
				else
					mc_q_strncpy(normal_map, arg, sizeof(normal_map));
			}
			continue;
		}

		/* In a stage. */
		if (!strcmp(low, "map") || !strcmp(low, "clampmap")) {
			char arg[MC_MAX_PATH];
			p = sh_token(p, arg, sizeof(arg));
			if (arg[0] != '$' && !cur.map[0])
				mc_q_strncpy(cur.map, arg, sizeof(cur.map));
		} else if (!strcmp(low, "animmap")) {
			char arg[64];
			p = sh_token(p, arg, sizeof(arg)); /* freq */
			char first[MC_MAX_PATH];
			p = sh_token(p, first, sizeof(first));
			if (!cur.map[0])
				mc_q_strncpy(cur.map, first, sizeof(cur.map));
		} else if (!strcmp(low, "blendfunc")) {
			cur.has_blendfunc = 1;
			char arg[64];
			p = sh_token(p, arg, sizeof(arg));
			sh_lower(arg);
			if (!strcmp(arg, "blend") || !strcmp(arg, "gl_src_alpha"))
				cur.alpha_mode = 2;
			else if (!strcmp(arg, "add"))
				cur.alpha_mode = 2;
			else if (!strcmp(arg, "filter") || !strcmp(arg, "gl_dst_color") ||
					 !strcmp(arg, "gl_zero"))
				/* multiplicative filter stage = decoration on top of base */
				cur.alpha_mode = -1;
			/* skip second arg if present */
			const char *peek = sh_skip(p);
			if (*peek != '{' && *peek != '}' && *peek) {
				char arg2[64];
				p = sh_token(p, arg2, sizeof(arg2));
				sh_lower(arg2);
				/* GL_ONE GL_ZERO is effectively opaque (replaces). */
				if (!strcmp(arg, "gl_one") && !strcmp(arg2, "gl_zero")) {
					cur.has_blendfunc = 0;
					cur.alpha_mode = -1;
				}
			}
		} else if (!strcmp(low, "alphafunc")) {
			char arg[64];
			p = sh_token(p, arg, sizeof(arg));
			sh_lower(arg);
			cur.alpha_mode = 1;
			if (!strcmp(arg, "ge128"))
				cur.alpha_cutoff = 128.0f / 255.0f;
			else if (!strcmp(arg, "gt0"))
				cur.alpha_cutoff = 1.0f / 255.0f;
			else if (!strcmp(arg, "lt128"))
				cur.alpha_cutoff = 128.0f / 255.0f;
		} else if (!strcmp(low, "tcgen")) {
			char arg[64];
			p = sh_token(p, arg, sizeof(arg));
			sh_lower(arg);
			if (!strcmp(arg, "environment"))
				cur.env_mapped = 1;
		}
	}

	/* Pick the diffuse stage:
	   1. prefer a stage whose map basename matches the shader basename
	      (e.g. shader "models/weapons2/betty/betty" -> "betty.tga")
	   2. otherwise prefer the last opaque-ish (no blendfunc) non-env
	      stage with a map (the conventional final base layer)
	   3. otherwise prefer the last non-env stage with a map
	   4. otherwise the first stage with a map
	   5. otherwise qer_editorimage. */
	const char *want_stem = mc_basename(name);
	int chosen = -1;
	for (int i = 0; i < num_stages; ++i) {
		if (!stages[i].map[0] || stages[i].env_mapped)
			continue;
		const char *bn = mc_basename(stages[i].map);
		char stem[MC_MAX_PATH];
		mc_q_strncpy(stem, bn, sizeof(stem));
		mc_strip_extension(stem);
		if (!strcasecmp(stem, want_stem)) {
			chosen = i;
			break;
		}
	}
	if (chosen < 0) {
		for (int i = num_stages - 1; i >= 0; --i) {
			if (stages[i].map[0] && !stages[i].env_mapped && !stages[i].has_blendfunc) {
				chosen = i;
				break;
			}
		}
	}
	if (chosen < 0) {
		for (int i = num_stages - 1; i >= 0; --i) {
			if (stages[i].map[0] && !stages[i].env_mapped) {
				chosen = i;
				break;
			}
		}
	}
	if (chosen < 0) {
		for (int i = 0; i < num_stages; ++i) {
			if (stages[i].map[0]) {
				chosen = i;
				break;
			}
		}
	}

	char map_path[MC_MAX_PATH];
	int alpha_mode = -1;
	float alpha_cutoff = 0.5f;
	if (chosen >= 0) {
		mc_q_strncpy(map_path, stages[chosen].map, sizeof(map_path));
		alpha_mode = stages[chosen].alpha_mode;
		alpha_cutoff = stages[chosen].alpha_cutoff;
		/* If this isn't the first map-bearing stage, any alphaFunc /
		   blend on it is for compositing over the earlier base layers
		   (e.g. WoP weapons paint a decal on top of an animated water
		   stage).  Standalone in a glTF viewer that would mask out the
		   transparent regions of the texture, so treat as opaque. */
		int first_map = -1;
		for (int i = 0; i < num_stages; ++i) {
			if (stages[i].map[0]) { first_map = i; break; }
		}
		if (chosen != first_map)
			alpha_mode = 0;
	} else if (editor_image[0]) {
		mc_q_strncpy(map_path, editor_image, sizeof(map_path));
	} else {
		map_path[0] = 0;
	}

	for (int i = 0; i < m->numSurfaces; ++i) {
		mc_surface_t *s = &m->surfaces[i];
		/* MD3 surface shaders sometimes carry a .tga/.jpg/.png suffix
		   (e.g. "models/.../yellflare.tga") while shader scripts use
		   the extensionless form. Match either way. */
		char surf_stem[MC_MAX_PATH];
		mc_q_strncpy(surf_stem, s->shader, sizeof(surf_stem));
		mc_strip_extension(surf_stem);
		if (strcasecmp(s->shader, name) && strcasecmp(surf_stem, name))
			continue;
		if (map_path[0] && !s->texture[0])
			mc_q_strncpy(s->texture, map_path, sizeof(s->texture));
		if (two_sided >= 0)
			s->two_sided = two_sided;
		if (alpha_mode >= 0) {
			s->alpha_mode = alpha_mode;
			if (alpha_mode == 1)
				s->alpha_cutoff = alpha_cutoff;
		}
		if (surfaceparm[0])
			mc_q_strncpy(s->surfaceparm, surfaceparm, sizeof(s->surfaceparm));
		if (deform[0])
			mc_q_strncpy(s->deform, deform, sizeof(s->deform));
		if (normal_map[0] && !s->normal_map[0])
			mc_q_strncpy(s->normal_map, normal_map, sizeof(s->normal_map));
		if (normal_height_map[0] && !s->normal_height_map[0])
			mc_q_strncpy(s->normal_height_map, normal_height_map, sizeof(s->normal_height_map));
		if (emissive_map[0] && !s->emissive_map[0])
			mc_q_strncpy(s->emissive_map, emissive_map, sizeof(s->emissive_map));
		/* Snapshot the raw stanza body so a glTF round-trip can re-emit
		   the full set of stages verbatim instead of regenerating a
		   stripped-down approximation from the parsed metadata. */
		if (body && body_len > 0) {
			free(s->q3_shader_body);
			s->q3_shader_body = (char *)mc_malloc(body_len + 1);
			if (s->q3_shader_body) {
				memcpy(s->q3_shader_body, body, body_len);
				s->q3_shader_body[body_len] = 0;
			}
		}
	}
}

int mc_load_q3shader(const char *path, mc_model_t *m) {
	size_t sz = 0;
	unsigned char *raw = mc_read_file(path, &sz);
	if (!raw)
		return -1;
	const char *src = (const char *)raw;
	const char *p = src;
	int found = 0;

	for (;;) {
		char name[MC_MAX_QPATH];
		const char *next = sh_token(p, name, sizeof(name));
		if (!next || !name[0])
			break;
		p = next;
		/* Expect a '{' opening the stanza body. */
		const char *peek = sh_skip(p);
		if (*peek != '{')
			continue;
		p = peek + 1;

		/* Walk balanced braces to find the matching close. */
		const char *body = p;
		int depth = 1;
		while (*p && depth > 0) {
			p = sh_skip(p);
			if (*p == '{') {
				++depth;
				++p;
			} else if (*p == '}') {
				--depth;
				if (depth == 0)
					break;
				++p;
			} else {
				char tmp[256];
				const char *n2 = sh_token(p, tmp, sizeof(tmp));
				if (!n2)
					break;
				p = n2;
			}
		}
		if (depth != 0)
			break;
		const char *bodyEnd = p; /* points at the matching '}' */
		shader_apply(m, name, body, (size_t)(bodyEnd - body));
		++found;
		if (*p == '}')
			++p;
	}

	free(raw);
	MC_LOG("parsed %s (%d shader stanza%s)\n", path, found, found == 1 ? "" : "s");
	return 0;
}

/* ------------------------------------------------------------------ */
/* .skin file support                                                 */
/* ------------------------------------------------------------------ */

/* Parse a .skin file into a list of (surface,shader) entries.  Returns
   the number of entries collected.  Used both by the legacy
   `mc_load_q3skin` (which patches an mc_model_t in place) and by the
   player-bundle loader which keeps every variant verbatim. */
static int parse_q3skin(const unsigned char *raw, size_t sz, mc_skin_entry_t **out) {
	int cap = 0, n = 0;
	mc_skin_entry_t *list = NULL;
	const char *p = (const char *)raw;
	const char *end = p + sz;
	while (p < end) {
		const char *eol = p;
		while (eol < end && *eol != '\n' && *eol != '\r')
			++eol;
		size_t len = (size_t)(eol - p);
		char line[512];
		if (len >= sizeof(line))
			len = sizeof(line) - 1;
		memcpy(line, p, len);
		line[len] = 0;
		p = eol;
		while (p < end && (*p == '\n' || *p == '\r'))
			++p;

		char *hash = strchr(line, '#');
		if (hash)
			*hash = 0;
		char *cmt = strstr(line, "//");
		if (cmt)
			*cmt = 0;

		char *comma = strchr(line, ',');
		if (!comma)
			continue;
		*comma = 0;
		char *sname = line;
		char *texture = comma + 1;
		while (*sname && (*sname == ' ' || *sname == '\t'))
			++sname;
		char *e = sname + strlen(sname);
		while (e > sname && (e[-1] == ' ' || e[-1] == '\t'))
			*--e = 0;
		while (*texture && (*texture == ' ' || *texture == '\t'))
			++texture;
		e = texture + strlen(texture);
		while (e > texture && (e[-1] == ' ' || e[-1] == '\t'))
			*--e = 0;

		if (!sname[0])
			continue;
		if (n == cap) {
			cap = cap ? cap * 2 : 8;
			list = (mc_skin_entry_t *)mc_realloc(list, (size_t)cap * sizeof(mc_skin_entry_t));
		}
		mc_q_strncpy(list[n].surface, sname, sizeof(list[n].surface));
		mc_q_strncpy(list[n].shader, texture, sizeof(list[n].shader));
		++n;
	}
	*out = list;
	return n;
}

int mc_load_q3skin_variant(const char *path, mc_skin_variant_t *out) {
	size_t sz = 0;
	unsigned char *raw = mc_read_file(path, &sz);
	if (!raw)
		return -1;
	free(out->entries);
	out->entries = NULL;
	out->numEntries = parse_q3skin(raw, sz, &out->entries);
	free(raw);
	return 0;
}

int mc_save_q3skin_variant(const char *path, const mc_skin_variant_t *v) {
	FILE *f = fopen(path, "wb");
	if (!f) {
		MC_ERR("error: cannot open '%s' for writing\n", path);
		return -1;
	}
	for (int i = 0; i < v->numEntries; ++i) {
		fprintf(f, "%s,%s\n", v->entries[i].surface, v->entries[i].shader);
	}
	fclose(f);
	return 0;
}

int mc_load_q3skin(const char *path, mc_model_t *m) {
	size_t sz = 0;
	unsigned char *raw = mc_read_file(path, &sz);
	if (!raw)
		return -1;

	mc_skin_entry_t *entries = NULL;
	int n = parse_q3skin(raw, sz, &entries);
	free(raw);
	int hits = 0;
	for (int i = 0; i < n; ++i) {
		const char *sname = entries[i].surface;
		const char *texture = entries[i].shader;
		if (!sname[0] || !texture[0])
			continue;
		if (!strncmp(sname, "tag_", 4))
			continue;
		for (int si = 0; si < m->numSurfaces; ++si) {
			mc_surface_t *s = &m->surfaces[si];
			if (strcasecmp(s->name, sname))
				continue;
			mc_q_strncpy(s->shader, texture, sizeof(s->shader));
			s->texture[0] = 0;
			++hits;
			break;
		}
	}
	free(entries);
	MC_LOG("parsed %s (%d surface override%s)\n", path, hits, hits == 1 ? "" : "s");
	return 0;
}

/* ------------------------------------------------------------------ */
/* Auto-discover .shader files under the asset roots                  */
/* ------------------------------------------------------------------ */


#ifdef _WIN32
#include <windows.h>
#include <sys/stat.h>
#define MC_STAT_STRUCT _stat
#define MC_STAT_FUNC _stat
#else
#include <dirent.h>
#include <sys/stat.h>
#define MC_STAT_STRUCT stat
#define MC_STAT_FUNC stat
#endif

static void scan_dir_for_shaders(const char *dir, const char *const *asset_roots, mc_model_t *m, int depth, int *count);

/* Module-global config so the CLI can tune scan depth and add extra
   --shader-path roots without changing every call site. */
static int g_shader_max_depth = 6;
static char **g_shader_extra_paths = NULL;
static int g_shader_extra_count = 0;

void mc_q3shader_set_max_depth(int depth) {
	if (depth < 0) depth = 0;
	if (depth > 32) depth = 32; /* sanity cap */
	g_shader_max_depth = depth;
}

void mc_q3shader_add_search_path(const char *dir) {
	if (!dir || !dir[0]) return;
	g_shader_extra_paths = (char **)mc_realloc(g_shader_extra_paths,
		sizeof(char *) * (size_t)(g_shader_extra_count + 1));
	g_shader_extra_paths[g_shader_extra_count++] = strdup(dir);
}

static void try_apply_shader_file(const char *path, mc_model_t *m, int *count) {
	/* Quick filter: only files whose name ends in ".shader". */
	size_t l = strlen(path);
	if (l < 7 || strcasecmp(path + l - 7, ".shader"))
		return;
	if (mc_load_q3shader(path, m) == 0)
		++(*count);
}

/* Callback context for PK3 shader scanning. */
typedef struct {
	mc_model_t *m;
	int *count;
} pk3_shader_ctx_t;

static void pk3_shader_cb(const char *pk3, const char *entry, void *user) {
	pk3_shader_ctx_t *ctx = (pk3_shader_ctx_t *)user;
	size_t sz = 0;
	unsigned char *data = mc_pk3_read_entry(pk3, entry, &sz);
	if (!data) return;
	/* mc_load_q3shader expects a file path; write to a temp file. */
	char tmp[MC_MAX_PATH];
	snprintf(tmp, sizeof(tmp), "/tmp/mc_pk3_%s", strrchr(entry, '/') ? strrchr(entry, '/') + 1 : entry);
	if (mc_write_file(tmp, data, sz) == 0) {
		if (mc_load_q3shader(tmp, ctx->m) == 0)
			++(*ctx->count);
		remove(tmp);
	}
	free(data);
}

static void try_apply_pk3(const char *path, mc_model_t *m, int *count) {
	if (!mc_pk3_is_pk3(path)) return;
	pk3_shader_ctx_t ctx = { m, count };
	mc_pk3_for_each(path, ".shader", pk3_shader_cb, &ctx);
}

static void scan_dir_for_shaders(const char *dir, const char *const *asset_roots, mc_model_t *m, int depth, int *count) {
	(void)asset_roots;
	if (depth > g_shader_max_depth)
		return;
#ifdef _WIN32
	char pattern[MC_MAX_PATH];
	snprintf(pattern, sizeof(pattern), "%s\\*", dir);
	WIN32_FIND_DATAA fd;
	HANDLE h = FindFirstFileA(pattern, &fd);
	if (h == INVALID_HANDLE_VALUE)
		return;
	do {
		if (!strcmp(fd.cFileName, ".") || !strcmp(fd.cFileName, ".."))
			continue;
		char child[MC_MAX_PATH];
		snprintf(child, sizeof(child), "%s\\%s", dir, fd.cFileName);
		if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)
			scan_dir_for_shaders(child, asset_roots, m, depth + 1, count);
		else {
			try_apply_shader_file(child, m, count);
			try_apply_pk3(child, m, count);
		}
	} while (FindNextFileA(h, &fd));
	FindClose(h);
#else
	DIR *d = opendir(dir);
	if (!d)
		return;
	struct dirent *de;
	while ((de = readdir(d)) != NULL) {
		if (!strcmp(de->d_name, ".") || !strcmp(de->d_name, ".."))
			continue;
		char child[MC_MAX_PATH];
		snprintf(child, sizeof(child), "%s/%s", dir, de->d_name);
		struct MC_STAT_STRUCT st;
		if (MC_STAT_FUNC(child, &st) != 0)
			continue;
		if (S_ISDIR(st.st_mode))
			scan_dir_for_shaders(child, asset_roots, m, depth + 1, count);
		else if (S_ISREG(st.st_mode)) {
			try_apply_shader_file(child, m, count);
			try_apply_pk3(child, m, count);
		}
	}
	closedir(d);
#endif
}

int mc_autoload_shaders(const char *const *asset_roots, mc_model_t *m) {
	if (!m || m->numSurfaces <= 0)
		return 0;
	int count = 0;
	/* Walk asset_roots first (the canonical Q3 layout: <root>/scripts and
	   <root>/ *.pk3dir/scripts), then any --shader-path the user added.
	   Extra paths are scanned recursively from their root so users can
	   point at "baseq3/" and have us find scripts/ underneath. */
	for (int i = 0; asset_roots && asset_roots[i]; ++i) {
		/* Look for a "scripts" sibling (the standard Q3 layout). */
		char scripts[MC_MAX_PATH];
		snprintf(scripts, sizeof(scripts), "%s/scripts", asset_roots[i]);
		struct MC_STAT_STRUCT st;
		if (MC_STAT_FUNC(scripts, &st) == 0 && S_ISDIR(st.st_mode)) {
			scan_dir_for_shaders(scripts, asset_roots, m, 0, &count);
		}
		/* Also look for *.pk3dir/scripts under this root. */
		char pk3dirs[MC_MAX_PATH];
		mc_q_strncpy(pk3dirs, asset_roots[i], sizeof(pk3dirs));
#ifdef _WIN32
		WIN32_FIND_DATAA fd;
		char pat[MC_MAX_PATH];
		snprintf(pat, sizeof(pat), "%s\\*.pk3dir", pk3dirs);
		HANDLE h = FindFirstFileA(pat, &fd);
		if (h != INVALID_HANDLE_VALUE) {
			do {
				if (!(fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY))
					continue;
				char sub[MC_MAX_PATH];
				snprintf(sub, sizeof(sub), "%s\\%s\\scripts", pk3dirs, fd.cFileName);
				scan_dir_for_shaders(sub, asset_roots, m, 0, &count);
			} while (FindNextFileA(h, &fd));
			FindClose(h);
		}
#else
		DIR *d = opendir(pk3dirs);
		if (d) {
			struct dirent *de;
			while ((de = readdir(d)) != NULL) {
				size_t nl = strlen(de->d_name);
				if (nl < 8 || strcmp(de->d_name + nl - 7, ".pk3dir"))
					continue;
				char sub[MC_MAX_PATH];
				snprintf(sub, sizeof(sub), "%s/%s/scripts", pk3dirs, de->d_name);
				struct MC_STAT_STRUCT sst;
				if (MC_STAT_FUNC(sub, &sst) == 0 && S_ISDIR(sst.st_mode))
					scan_dir_for_shaders(sub, asset_roots, m, 0, &count);
			}
			closedir(d);
		}
#endif
	}
	/* Extra --shader-path roots: scan recursively for any *.shader. */
	for (int i = 0; i < g_shader_extra_count; ++i) {
		struct MC_STAT_STRUCT st;
		if (MC_STAT_FUNC(g_shader_extra_paths[i], &st) == 0 && S_ISDIR(st.st_mode))
			scan_dir_for_shaders(g_shader_extra_paths[i], asset_roots, m, 0, &count);
	}
	if (count)
		MC_LOG("auto-loaded %d shader file%s\n", count, count == 1 ? "" : "s");
	return count;
}
